export const couponsSeedData = [
  {
    code: 'WELCOME10',
    type: 'percentage',
    value: 10,
    description: '10% off for new customers',
    minPurchase: 50,
    status: 'active',
    usageLimit: 100,
    usageCount: 5,
  },
  {
    code: 'SAVE20',
    type: 'percentage',
    value: 20,
    description: '20% off orders over $200',
    minPurchase: 200,
    maxDiscount: 100,
    status: 'active',
    usageLimit: 50,
    usageCount: 12,
  },
  {
    code: 'FREESHIP',
    type: 'freeShipping',
    description: 'Free shipping on all orders',
    minPurchase: 100,
    status: 'active',
    usageLimit: 200,
    usageCount: 45,
  },
  {
    code: 'FIXED25',
    type: 'fixed',
    value: 25,
    description: '$25 off your order',
    minPurchase: 150,
    status: 'active',
    usageLimit: 75,
    usageCount: 8,
  },
  {
    code: 'EXPIRED',
    type: 'percentage',
    value: 50,
    description: 'Expired coupon for testing',
    status: 'expired',
    validFrom: new Date('2024-01-01'),
    validUntil: new Date('2024-12-31'),
  },
];
