export const productsSeedData = [
  // Electronics - Laptops
  {
    title: 'MacBook Pro 16"',
    slug: 'macbook-pro-16',
    description: 'Powerful laptop with M2 chip, perfect for professionals and creatives.',
    price: 2499,
    compareAtPrice: 2799,
    sku: 'MBP-16-M2',
    category: 'laptops',
    status: 'active',
    trackQuantity: true,
    quantity: 15,
    lowStockThreshold: 5,
    imageUrl: 'https://picsum.photos/seed/macbook-pro/800/600',
    variants: [
      { name: 'M2 Pro / 512GB', sku: 'MBP-16-M2P-512', price: 2499, quantity: 8 },
      { name: 'M2 Max / 1TB', sku: 'MBP-16-M2M-1TB', price: 3499, quantity: 7 },
    ]
  },
  // Electronics - Smartphones
  {
    title: 'iPhone 15 Pro',
    slug: 'iphone-15-pro',
    description: 'Latest iPhone with titanium design and powerful A17 Pro chip.',
    price: 999,
    compareAtPrice: 1099,
    sku: 'IP15-PRO',
    category: 'smartphones',
    status: 'active',
    trackQuantity: true,
    quantity: 50,
    lowStockThreshold: 10,
    imageUrl: 'https://picsum.photos/seed/iphone-15-pro/800/600',
    variants: [
      { name: '128GB - Natural Titanium', sku: 'IP15-PRO-128-NT', price: 999, quantity: 15 },
      { name: '256GB - Natural Titanium', sku: 'IP15-PRO-256-NT', price: 1099, quantity: 15 },
      { name: '256GB - Blue Titanium', sku: 'IP15-PRO-256-BT', price: 1099, quantity: 10 },
      { name: '512GB - Black Titanium', sku: 'IP15-PRO-512-BK', price: 1299, quantity: 10 },
    ]
  },
  {
    title: 'iPad Air',
    slug: 'ipad-air',
    description: 'Lightweight tablet with M1 chip, perfect for work and play.',
    price: 599,
    sku: 'IPAD-AIR-M1',
    category: 'smartphones',
    status: 'active',
    trackQuantity: true,
    quantity: 30,
    lowStockThreshold: 8,
    imageUrl: 'https://picsum.photos/seed/ipad-air/800/600',
  },
  // Electronics - Accessories
  {
    title: 'AirPods Pro',
    slug: 'airpods-pro',
    description: 'Active noise cancellation for immersive sound.',
    price: 249,
    sku: 'APP-2ND',
    category: 'accessories',
    status: 'active',
    trackQuantity: true,
    quantity: 100,
    lowStockThreshold: 20,
    imageUrl: 'https://picsum.photos/seed/airpods-pro/800/600',
  },
  {
    title: 'Magic Keyboard',
    slug: 'magic-keyboard',
    description: 'Wireless keyboard with rechargeable battery.',
    price: 99,
    sku: 'MK-2021',
    category: 'accessories',
    status: 'active',
    trackQuantity: true,
    quantity: 45,
    lowStockThreshold: 10,
    imageUrl: 'https://picsum.photos/seed/magic-keyboard/800/600',
  },
  {
    title: 'USB-C Hub',
    slug: 'usb-c-hub',
    description: '7-in-1 USB-C hub with HDMI, USB 3.0, and SD card reader.',
    price: 49,
    compareAtPrice: 79,
    sku: 'HUB-7IN1',
    category: 'accessories',
    status: 'active',
    trackQuantity: true,
    quantity: 80,
    lowStockThreshold: 15,
    imageUrl: 'https://picsum.photos/seed/usb-c-hub/800/600',
  },
  // Clothing - Men
  {
    title: 'Classic White T-Shirt',
    slug: 'classic-white-tshirt',
    description: 'Essential white t-shirt made from premium cotton.',
    price: 29,
    sku: 'TSHIRT-WHT',
    category: 'men',
    status: 'active',
    trackQuantity: true,
    quantity: 200,
    lowStockThreshold: 30,
    imageUrl: 'https://picsum.photos/seed/white-tshirt/800/600',
    variants: [
      { name: 'Small', sku: 'TSHIRT-WHT-S', quantity: 50 },
      { name: 'Medium', sku: 'TSHIRT-WHT-M', quantity: 60 },
      { name: 'Large', sku: 'TSHIRT-WHT-L', quantity: 50 },
      { name: 'X-Large', sku: 'TSHIRT-WHT-XL', quantity: 40 },
    ]
  },
  {
    title: 'Slim Fit Jeans',
    slug: 'slim-fit-jeans',
    description: 'Modern slim fit jeans in classic blue denim.',
    price: 79,
    sku: 'JEANS-SLIM',
    category: 'men',
    status: 'active',
    trackQuantity: true,
    quantity: 120,
    lowStockThreshold: 20,
    imageUrl: 'https://picsum.photos/seed/slim-jeans/800/600',
    variants: [
      { name: '30 - Blue', sku: 'JEANS-SLIM-30-BLU', quantity: 20 },
      { name: '32 - Blue', sku: 'JEANS-SLIM-32-BLU', quantity: 30 },
      { name: '34 - Blue', sku: 'JEANS-SLIM-34-BLU', quantity: 30 },
      { name: '32 - Black', sku: 'JEANS-SLIM-32-BLK', quantity: 20 },
      { name: '34 - Black', sku: 'JEANS-SLIM-34-BLK', quantity: 20 },
    ]
  },
  {
    title: 'Hooded Sweatshirt',
    slug: 'hooded-sweatshirt',
    description: 'Comfortable hoodie perfect for casual wear.',
    price: 59,
    sku: 'HOODIE',
    category: 'men',
    status: 'active',
    trackQuantity: true,
    quantity: 150,
    lowStockThreshold: 25,
    imageUrl: 'https://picsum.photos/seed/hooded-sweatshirt/800/600',
    variants: [
      { name: 'S - Gray', sku: 'HOODIE-S-GRY', quantity: 25 },
      { name: 'M - Gray', sku: 'HOODIE-M-GRY', quantity: 35 },
      { name: 'L - Gray', sku: 'HOODIE-L-GRY', quantity: 30 },
      { name: 'M - Navy', sku: 'HOODIE-M-NVY', quantity: 30 },
      { name: 'L - Navy', sku: 'HOODIE-L-NVY', quantity: 30 },
    ]
  },
  {
    title: 'Running Shoes',
    slug: 'running-shoes',
    description: 'Lightweight running shoes with superior cushioning.',
    price: 129,
    sku: 'SHOES-RUN',
    category: 'men',
    status: 'active',
    trackQuantity: true,
    quantity: 90,
    lowStockThreshold: 15,
    imageUrl: 'https://picsum.photos/seed/running-shoes/800/600',
    variants: [
      { name: 'Size 8', sku: 'SHOES-RUN-8', quantity: 15 },
      { name: 'Size 9', sku: 'SHOES-RUN-9', quantity: 20 },
      { name: 'Size 10', sku: 'SHOES-RUN-10', quantity: 20 },
      { name: 'Size 11', sku: 'SHOES-RUN-11', quantity: 20 },
      { name: 'Size 12', sku: 'SHOES-RUN-12', quantity: 15 },
    ]
  },
  {
    title: 'Leather Jacket',
    slug: 'leather-jacket',
    description: 'Premium leather jacket with classic design.',
    price: 299,
    sku: 'JACKET-LTH',
    category: 'men',
    status: 'active',
    trackQuantity: true,
    quantity: 30,
    lowStockThreshold: 5,
    imageUrl: 'https://picsum.photos/seed/leather-jacket/800/600',
    variants: [
      { name: 'Small', sku: 'JACKET-LTH-S', quantity: 8 },
      { name: 'Medium', sku: 'JACKET-LTH-M', quantity: 10 },
      { name: 'Large', sku: 'JACKET-LTH-L', quantity: 8 },
      { name: 'X-Large', sku: 'JACKET-LTH-XL', quantity: 4 },
    ]
  },
  // Clothing - Women
  {
    title: 'Summer Dress',
    slug: 'summer-dress',
    description: 'Light and airy summer dress with floral pattern.',
    price: 89,
    sku: 'DRESS-SUM',
    category: 'women',
    status: 'active',
    trackQuantity: true,
    quantity: 60,
    lowStockThreshold: 10,
    imageUrl: 'https://picsum.photos/seed/summer-dress/800/600',
    variants: [
      { name: 'XS - Floral', sku: 'DRESS-SUM-XS-FLR', quantity: 10 },
      { name: 'S - Floral', sku: 'DRESS-SUM-S-FLR', quantity: 15 },
      { name: 'M - Floral', sku: 'DRESS-SUM-M-FLR', quantity: 15 },
      { name: 'L - Floral', sku: 'DRESS-SUM-L-FLR', quantity: 10 },
      { name: 'S - Solid', sku: 'DRESS-SUM-S-SOL', quantity: 10 },
    ]
  },
  // Home & Garden - Furniture
  {
    title: 'Office Chair',
    slug: 'office-chair',
    description: 'Ergonomic office chair with lumbar support.',
    price: 399,
    sku: 'CHAIR-OFF',
    category: 'furniture',
    status: 'active',
    trackQuantity: true,
    quantity: 25,
    lowStockThreshold: 5,
    imageUrl: 'https://picsum.photos/seed/office-chair/800/600',
  },
  {
    title: 'Standing Desk',
    slug: 'standing-desk',
    description: 'Adjustable standing desk with electric motor.',
    price: 699,
    sku: 'DESK-STAND',
    category: 'furniture',
    status: 'active',
    trackQuantity: true,
    quantity: 15,
    lowStockThreshold: 3,
    imageUrl: 'https://picsum.photos/seed/standing-desk/800/600',
  },
  {
    title: 'Bookshelf',
    slug: 'bookshelf',
    description: '5-tier wooden bookshelf with modern design.',
    price: 249,
    sku: 'SHELF-BOOK',
    category: 'furniture',
    status: 'active',
    trackQuantity: true,
    quantity: 20,
    lowStockThreshold: 5,
    imageUrl: 'https://picsum.photos/seed/bookshelf/800/600',
  },
  // Home & Garden - Decor
  {
    title: 'Table Lamp',
    slug: 'table-lamp',
    description: 'Modern table lamp with adjustable brightness.',
    price: 79,
    sku: 'LAMP-TBL',
    category: 'decor',
    status: 'active',
    trackQuantity: true,
    quantity: 50,
    lowStockThreshold: 10,
    imageUrl: 'https://picsum.photos/seed/table-lamp/800/600',
  },
  {
    title: 'Throw Pillow Set',
    slug: 'throw-pillow-set',
    description: 'Set of 4 decorative throw pillows.',
    price: 49,
    sku: 'PILLOW-SET',
    category: 'decor',
    status: 'active',
    trackQuantity: true,
    quantity: 75,
    lowStockThreshold: 15,
    imageUrl: 'https://picsum.photos/seed/throw-pillows/800/600',
  },
  {
    title: 'Wall Art Canvas',
    slug: 'wall-art-canvas',
    description: 'Large canvas print with abstract design.',
    price: 129,
    sku: 'ART-CANVAS',
    category: 'decor',
    status: 'active',
    trackQuantity: true,
    quantity: 40,
    lowStockThreshold: 8,
    imageUrl: 'https://picsum.photos/seed/wall-art/800/600',
  },
  {
    title: 'Plant Pot Set',
    slug: 'plant-pot-set',
    description: 'Set of 3 ceramic plant pots with drainage.',
    price: 39,
    sku: 'POT-SET',
    category: 'decor',
    status: 'active',
    trackQuantity: true,
    quantity: 90,
    lowStockThreshold: 20,
    imageUrl: 'https://picsum.photos/seed/plant-pots/800/600',
  },
  {
    title: 'Area Rug',
    slug: 'area-rug',
    description: 'Large area rug with geometric pattern.',
    price: 199,
    sku: 'RUG-AREA',
    category: 'decor',
    status: 'active',
    trackQuantity: true,
    quantity: 30,
    lowStockThreshold: 5,
    imageUrl: 'https://picsum.photos/seed/area-rug/800/600',
  },
];
